# Site settings
author: Lindsay Parr
title: Day-to-Day Data
header-img: img/home-bg.png
email: lwcislo2@gmail.com
copyright_name: Lindsay Parr
description: > # this means to ignore newlines until "baseurl:"
  An in-depth look at the data processes powering your everyday.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lparr

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
